/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DishDishIdRouteImport } from './routes/dish.$dishId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DishDishIdRoute = DishDishIdRouteImport.update({
  id: '/dish/$dishId',
  path: '/dish/$dishId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dish/$dishId': typeof DishDishIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dish/$dishId': typeof DishDishIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dish/$dishId': typeof DishDishIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dish/$dishId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dish/$dishId'
  id: '__root__' | '/' | '/dish/$dishId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DishDishIdRoute: typeof DishDishIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dish/$dishId': {
      id: '/dish/$dishId'
      path: '/dish/$dishId'
      fullPath: '/dish/$dishId'
      preLoaderRoute: typeof DishDishIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DishDishIdRoute: DishDishIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
